---
- name: checking confluence start-up file to varify confluence installation
  ansible.builtin.stat:
    path: "{{ confluence.install }}/bin/start-confluence.sh"
  register: file_data

- name: untar confluence binary to confluence installation directory
  ansible.builtin.unarchive:
    src: "{{ common.media }}/atlassian-confluence-{{ confluence.version }}.tar"
    dest: "{{ confluence.install }}"
    owner: "{{ confluence.user }}"
    group: "{{ confluence.group }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: not file_data.stat.exists

- name: update the confluence init property file with home directory
  ansible.builtin.lineinfile:
    path: "{{ confluence.install }}/confluence/WEB-INF/classes/confluence-init.properties"
    line: "confluence.home={{ confluence.local_home }}"
    state: present

- name: update the setenv.bat file to add the synchrony url
  ansible.builtin.lineinfile:
    path: "{{ confluence.install }}/bin/setenv.sh"
    insertbefore: '^export CATALINA_OPTS'
    line: 'CATALINA_OPTS="-Dsynchrony.service.url=http://{{ confluence.url }}/synchrony/v1 ${CATALINA_OPTS}"'
    state: present

- name: create a confluence service file
  ansible.builtin.template:
    src: "confluence-service.j2"
    dest: "/usr/lib/systemd/system/{{ confluence.service }}.service"
    mode: "0644"
  register: service_status

- name: enable confluence service
  ansible.builtin.systemd_service:
    name: "{{ confluence.service }}.service"
    enabled: true
    daemon_reload: true
  when: service_status.changed
