#SPDX-License-Identifier: MIT-0
---
# https://confluence.atlassian.com/conf91/installing-confluence-on-linux-from-archive-file-1442849164.html
# /var/atlassian/confluence/logs/atlassian-confluence.log
# init Confluence is ready to serve
# tasks file for confluence
- name: prepare confluence servers for installing confluence
  include_tasks: prepare-confluence.yml

- name: configure confluence as a service
  include_tasks: configure-confluence.yml

- name: include task to mount efs file system
  include_tasks: mount-efs.yml

- name: include task to configure database
  include_tasks: database-confluence.yml
  when: ec2_info.instances[0]['placement']['availability_zone'] == region.zone1

- name: start confluence on secondary
  include_tasks: secondary-confluence.yml
  when: ec2_info.instances[0]['placement']['availability_zone'] == region.zone2
