---
- name: create confluence and postgres users on confluence servers
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash  # set the user’s shell.
  loop:
    - "{{ confluence.user }}"
    - "{{ db.user }}"

- name: elevate confluence user as sudoer
  ansible.builtin.template:
    src: confluence-user.j2
    dest: "/etc/sudoers.d/{{ confluence.user }}"

- name: create confluence install, local and shared home directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.src }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    recurse: yes
  loop:
    - { src: "{{confluence.install}}", owner: "{{confluence.user}}", group: "{{confluence.group}}", mode: "u=rwx,go-rwx" }
    - { src: "{{confluence.local_home}}", owner: "{{confluence.user}}", group: "{{confluence.group}}", mode: "u=rwx,go-rwx" }
    - { src: "{{confluence.shared_home}}", owner: "{{confluence.user}}", group: "{{confluence.group}}", mode: "u=rwx,go-rwx" }

- name: download confluence package from s3 bucket
  amazon.aws.s3_object:
    region: "{{ region.name }}"
    bucket: "{{ s3.bucket }}"
    object: "{{ s3.object }}/{{ item }}"
    dest: "{{ common.media }}/{{ item }}"
    mode: get
    overwrite: different # will not download file if file checksum match
  loop:
    - "atlassian-confluence-{{ confluence.version }}.tar"

- name: make confluence package executable
  ansible.builtin.file:
    path: "{{ common.media }}/{{ item }}"
    mode: +x
  loop:
    - "atlassian-confluence-{{ confluence.version }}.tar"

- name: setup postgres connection file
  ansible.builtin.template:
    src: pgpass.j2
    dest: "/home/{{ db.user }}/.pgpass"
    owner: "{{ db.user }}"
    mode: "400"
