---
- name: update all dnf packages on ec2 instance
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: install a list of common dnf packages
  ansible.builtin.dnf:
    name: "{{ packages.dnf }}"
    state: present
  register: dnf_common

- name: clean dnf metadata cache
  ansible.builtin.command: dnf clean metadata
  when: dnf_common.changed

- name: install pip packages
  ansible.builtin.pip: "name={{ item }} state=present"
  with_items: "{{ packages.pip }}"