#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: include task file to install common softwares
  include_tasks: install.yml

- name: include task file to execute common os related tasks
  include_tasks: set_hostname.yml